## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# check dimention: ndim
scalar.ndim

0

In [5]:
# check shape: shape
scalar.shape

torch.Size([])

In [15]:
# or size
scalar.size()

torch.Size([])

In [6]:
# get the Python value: item()
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [12]:
# item() does not work for a vector
vector.item()

ValueError: only one element tensors can be converted to Python scalars

In [16]:
vector.numpy()

array([4, 5], dtype=int64)

In [17]:
# note if requires_grad used, we need to detach() first
vector.detach().numpy()

array([4, 5], dtype=int64)

In [19]:
# matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]
                        ])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
MATRIX.size()

torch.Size([2, 2])

In [23]:
MATRIX.numpy()

array([[ 7,  8],
       [ 9, 10]], dtype=int64)

In [25]:
# note if requires_grad used, we need to detach() first
MATRIX.detach().numpy()

array([[ 7,  8],
       [ 9, 10]], dtype=int64)

In [27]:
# tensor
TENSOR = torch.tensor([[
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

In [30]:
TENSOR.size()

torch.Size([1, 3, 3])

In [31]:
TENSOR.numpy()

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int64)

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

### Random tensors

In [34]:
random_tensor = torch.rand(size=(4,5))
random_tensor, random_tensor.dtype

(tensor([[0.0452, 0.4007, 0.4163, 0.6382, 0.5223],
         [0.6433, 0.0515, 0.7467, 0.9439, 0.4486],
         [0.4071, 0.6674, 0.6118, 0.1624, 0.9981],
         [0.6893, 0.1092, 0.1425, 0.2615, 0.5549]]),
 torch.float32)

In [35]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zeros and ones

In [37]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range and tensors like

In [39]:
zero_to_ten = torch.arange(start=0, end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which is which can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.

The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [41]:
float_32_tensor = torch.tensor([3.0,4.0,5.0],dtype=torch.float32,device=None,requires_grad=False)
float_32_tensor

tensor([3., 4., 5.])

### Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

Let's create a random tensor and find out details about it.

In [42]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3763, 0.8332, 0.2167, 0.1389],
        [0.8258, 0.2847, 0.3156, 0.8245],
        [0.8419, 0.6424, 0.4245, 0.1341]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
