## 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# check dimention: ndim
scalar.ndim

0

In [5]:
# check shape: shape
scalar.shape

torch.Size([])

In [15]:
# or size
scalar.size()

torch.Size([])

In [6]:
# get the Python value: item()
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [12]:
# item() does not work for a vector
vector.item()

ValueError: only one element tensors can be converted to Python scalars

In [16]:
vector.numpy()

array([4, 5], dtype=int64)

In [17]:
# note if requires_grad used, we need to detach() first
vector.detach().numpy()

array([4, 5], dtype=int64)

In [19]:
# matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]
                        ])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [20]:
MATRIX.ndim

2

In [21]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
MATRIX.size()

torch.Size([2, 2])

In [23]:
MATRIX.numpy()

array([[ 7,  8],
       [ 9, 10]], dtype=int64)

In [25]:
# note if requires_grad used, we need to detach() first
MATRIX.detach().numpy()

array([[ 7,  8],
       [ 9, 10]], dtype=int64)

In [27]:
# tensor
TENSOR = torch.tensor([[
                        [1,2,3],
                        [4,5,6],
                        [7,8,9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [28]:
TENSOR.ndim

3

In [29]:
TENSOR.shape

torch.Size([1, 3, 3])

In [30]:
TENSOR.size()

torch.Size([1, 3, 3])

In [31]:
TENSOR.numpy()

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int64)

Let's summarise.

| Name | What is it? | Number of dimensions | Lower or upper (usually/example) |
| ----- | ----- | ----- | ----- |
| **scalar** | a single number | 0 | Lower (`a`) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (`y`) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (`Q`) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (`X`) | 

### Random tensors

In [34]:
random_tensor = torch.rand(size=(4,5))
random_tensor, random_tensor.dtype

(tensor([[0.0452, 0.4007, 0.4163, 0.6382, 0.5223],
         [0.6433, 0.0515, 0.7467, 0.9439, 0.4486],
         [0.4071, 0.6674, 0.6118, 0.1624, 0.9981],
         [0.6893, 0.1092, 0.1425, 0.2615, 0.5549]]),
 torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape